# Generated by Django 4.2.3 on 2023-11-29 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('foto_perfil', models.ImageField(upload_to='images')),
                ('celular', models.IntegerField()),
                ('cpf', models.IntegerField()),
                ('endereco', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('foto_perfil', models.ImageField(upload_to='images')),
                ('celular', models.IntegerField()),
                ('cpf', models.IntegerField()),
                ('endereco', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.IntegerField()),
                ('servico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('duracao_prevista', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.cliente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.profissional')),
            ],
        ),
    ]
