# Generated by Django 4.2.3 on 2023-12-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_cliente_cidade_profissional_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cidade',
            field=models.CharField(default='', max_length=150),
        ),
    ]
