# Generated by Django 4.2.3 on 2023-12-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0007_profissional_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='servicoextra',
            field=models.CharField(default='', max_length=100),
        ),
    ]
