# Generated by Django 4.2.3 on 2023-12-11 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0008_profissional_servicoextra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='servicoextra',
        ),
    ]
