# Generated by Django 4.2.3 on 2023-12-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0010_profissional_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_profissional',
            field=models.BooleanField(blank=True, null=True, verbose_name=False),
        ),
        migrations.AddField(
            model_name='profissional',
            name='is_profissional',
            field=models.BooleanField(blank=True, null=True, verbose_name=True),
        ),
    ]
