# Generated by Django 4.2.3 on 2023-12-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0011_cliente_is_profissional_profissional_is_profissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='is_profissional',
            field=models.BooleanField(default=False, verbose_name=False),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='is_profissional',
            field=models.BooleanField(default=True, verbose_name=True),
        ),
    ]
