# Generated by Django 4.2.3 on 2023-12-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0012_alter_cliente_is_profissional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='is_profissional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='is_profissional',
            field=models.BooleanField(default=True),
        ),
    ]
