# Generated by Django 4.2.3 on 2023-12-12 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0013_contrato_ativo_contrato_confirmado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos_servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='images')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.profissional')),
            ],
        ),
    ]
