# Generated by Django 4.2.3 on 2023-12-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0015_alter_cliente_estado_alter_profissional_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default='Ifrn12345', max_length=15),
        ),
        migrations.AddField(
            model_name='profissional',
            name='senha',
            field=models.CharField(default='Ifrn12345', max_length=15),
        ),
    ]
